name: Angelic Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with: {python-version: '3.11'}
      - name: Install Flet
        run: pip install flet
      - name: Build APK
        run: flet build apk --module-name main
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SuccessionShield-APK
          path: build/apk/*.apk
